<?xml version="1.0"?>
<package format="3">
  <name>joystick_controller</name>
  <version>0.1.0</version>
  <description>Joystick to cmd_vel publisher using low-level /dev/input/js0 interface</description>

  <maintainer email="leejae0720@gmail.com">Jaehong Lee</maintainer>
  <license>TODO: insert license</license>

  <!-- Build tool dependencies -->
  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- Build/runtime dependencies -->
  <depend>rclcpp</depend>
  <depend>geometry_msgs</depend>
  
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
